import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/src/components/footer/Footer'
import NavBar from '@/src/components/navBar/NavBar'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Electronics',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}